/* ============================================================
   Waypoint demo data.
   Støtvig Hotel is grounded in its public profile (rating,
   amenities, price range); all reviews and the other listings
   are original illustrative samples for this prototype.
   ============================================================ */

export const LISTINGS = [
  {
    id: "stotvig",
    type: "Hotel",
    name: "Støtvig Hotel",
    place: "Larkollen, Østfold, Norway",
    rating: 4.5,
    reviewCount: 573,
    rank: "#1 of 1 hotels in Larkollen",
    price: "NOK 2,105 – 4,030 / night",
    tags: ["Beachfront", "Spa", "Bowling", "Dog-friendly"],
    gradient: ["#1d4e5f", "#5f9ea8", "#dce9e6"],
    icon: "⛵",
    about:
      "A modern coastal hotel on the Oslofjord, inspired by the classic Norwegian bathing hotels with a touch of New England atmosphere. 91 bright rooms, three restaurants and several bars, a full spa with indoor-to-outdoor pool and three saunas, plus bowling, tennis and direct beach access. About 55 minutes from Oslo and 15 minutes from Moss.",
    amenities: [
      "Free parking", "Free WiFi", "Indoor & outdoor pool", "Spa with 3 saunas",
      "Beach access", "Bowling alley", "Fitness room", "Breakfast included",
      "Three restaurants", "Conference facilities", "Kids' play area", "Sea-view rooms",
    ],
    subRatings: { Location: 4.7, Cleanliness: 4.8, Rooms: 4.6, "Sleep quality": 4.6, Service: 4.4, Value: 4.1 },
  },
  {
    id: "nordlys",
    type: "Hotel",
    name: "Nordlys Harbour Hotel",
    place: "Tromsø, Norway",
    rating: 4.6,
    reviewCount: 841,
    rank: "#3 of 27 hotels in Tromsø",
    price: "NOK 1,890 – 3,400 / night",
    tags: ["Northern lights", "Harbour view", "Sauna"],
    gradient: ["#0d1f3c", "#3a5f8a", "#bcd5e8"],
    icon: "❄",
    about:
      "Glass-fronted rooms over the Arctic harbour, a rooftop sauna with fjord views, and a wake-up call service when the aurora appears. Walking distance to the cable car and the Arctic Cathedral.",
    amenities: ["Aurora wake-up call", "Rooftop sauna", "Breakfast included", "Free WiFi", "Bar & bistro", "Ski storage", "Airport bus stop", "Harbour-view rooms"],
    subRatings: { Location: 4.8, Cleanliness: 4.7, Rooms: 4.5, "Sleep quality": 4.4, Service: 4.7, Value: 4.2 },
  },
  {
    id: "havblikk",
    type: "Hotel",
    name: "Havblikk Fyr Hotel",
    place: "Lofoten, Norway",
    rating: 4.8,
    reviewCount: 296,
    rank: "#1 of 11 hotels in Lofoten West",
    price: "NOK 2,600 – 4,800 / night",
    tags: ["Lighthouse", "Remote", "Adults preferred"],
    gradient: ["#243b3a", "#5e8a7a", "#e8efe6"],
    icon: "🗼",
    about:
      "A converted lighthouse station on the outer edge of Lofoten — twelve rooms, one long dining table, and the Atlantic on three sides. Dinner is a set menu of whatever the boats brought in that morning.",
    amenities: ["Set-menu dinner", "Library lounge", "Guided hikes", "Sea fishing", "Free parking", "Breakfast included", "No TV by design", "Storm-watching deck"],
    subRatings: { Location: 5.0, Cleanliness: 4.8, Rooms: 4.6, "Sleep quality": 4.8, Service: 4.9, Value: 4.4 },
  },
  {
    id: "granly",
    type: "Hotel",
    name: "Granly Skogshotell & Spa",
    place: "Lillehammer, Norway",
    rating: 4.2,
    reviewCount: 512,
    rank: "#4 of 15 hotels in Lillehammer",
    price: "NOK 1,450 – 2,700 / night",
    tags: ["Forest spa", "Family", "Ski bus"],
    gradient: ["#1e3325", "#4f7a51", "#dde8d5"],
    icon: "🌲",
    about:
      "Pine-forest resort ten minutes from the Olympic slopes. Big family rooms, an outdoor heated pool among the trees, and a kids' club during school holidays.",
    amenities: ["Outdoor heated pool", "Kids' club", "Ski bus stop", "Sauna & steam room", "Free parking", "Buffet restaurant", "Game room", "EV charging"],
    subRatings: { Location: 4.3, Cleanliness: 4.3, Rooms: 4.0, "Sleep quality": 4.2, Service: 4.3, Value: 4.1 },
  },
  {
    id: "kanalhuset",
    type: "Hotel",
    name: "Hotel Kanalhuset",
    place: "Copenhagen, Denmark",
    rating: 4.4,
    reviewCount: 1093,
    rank: "#12 of 130 hotels in Copenhagen",
    price: "DKK 1,200 – 2,300 / night",
    tags: ["Canal view", "Design", "Bikes included"],
    gradient: ["#37302a", "#8a7a5e", "#efe7d8"],
    icon: "🚲",
    about:
      "A converted 18th-century warehouse on the Christianshavn canal. Compact, beautifully designed rooms, free city bikes for every guest, and a courtyard café that locals actually use.",
    amenities: ["Free city bikes", "Courtyard café", "Organic breakfast", "Free WiFi", "Canal-view rooms", "Luggage room", "Late checkout option", "Pet friendly"],
    subRatings: { Location: 4.7, Cleanliness: 4.5, Rooms: 4.1, "Sleep quality": 4.2, Service: 4.5, Value: 4.3 },
  },
  {
    id: "lindencourt",
    type: "Hotel",
    name: "The Linden Court",
    place: "London, United Kingdom",
    rating: 4.1,
    reviewCount: 2210,
    rank: "#88 of 1,140 hotels in London",
    price: "£140 – £310 / night",
    tags: ["Townhouse", "Afternoon tea", "Garden square"],
    gradient: ["#2c2330", "#6b5a72", "#e9e2ec"],
    icon: "🫖",
    about:
      "A Georgian townhouse hotel on a quiet garden square in Bloomsbury. Creaky charm, proper afternoon tea, and the British Museum five minutes away on foot.",
    amenities: ["Afternoon tea", "Garden square access", "Concierge", "Free WiFi", "Library bar", "Room service", "Laundry", "Accessible rooms (limited)"],
    subRatings: { Location: 4.6, Cleanliness: 4.2, Rooms: 3.8, "Sleep quality": 3.9, Service: 4.4, Value: 3.9 },
  },
  {
    id: "sakurabay",
    type: "Hotel",
    name: "Sakura Bay Ryokan",
    place: "Hakone, Japan",
    rating: 4.9,
    reviewCount: 668,
    rank: "#2 of 64 ryokan in Hakone",
    price: "¥38,000 – ¥72,000 / night",
    tags: ["Onsen", "Kaiseki", "Mountain view"],
    gradient: ["#3a2230", "#a05a6e", "#f5e3e0"],
    icon: "♨",
    about:
      "Traditional ryokan with private open-air onsen baths and a ten-course kaiseki dinner served in-room. Tatami rooms look across the valley toward Mount Fuji on clear mornings.",
    amenities: ["Private onsen baths", "Kaiseki dinner", "In-room dining", "Yukata provided", "Tea ceremony", "Shuttle to station", "Garden", "Public baths"],
    subRatings: { Location: 4.8, Cleanliness: 5.0, Rooms: 4.9, "Sleep quality": 4.8, Service: 5.0, Value: 4.5 },
  },
  {
    id: "casadelfaro",
    type: "Hotel",
    name: "Casa del Faro",
    place: "Cinque Terre, Italy",
    rating: 4.3,
    reviewCount: 754,
    rank: "#5 of 38 hotels in Cinque Terre",
    price: "€160 – €390 / night",
    tags: ["Cliffside", "Sea view", "Romantic"],
    gradient: ["#2f4858", "#e07a5f", "#f7e8d0"],
    icon: "🍋",
    about:
      "Lemon-coloured guesthouse stacked into the cliff above the harbour. Steep stairs, unbeatable terraces, and breakfast with a view that does most of the talking.",
    amenities: ["Sea-view terraces", "Breakfast included", "Air conditioning", "Luggage porter (stairs!)", "Free WiFi", "Beach towels", "Limoncello welcome", "No elevator"],
    subRatings: { Location: 4.9, Cleanliness: 4.4, Rooms: 4.0, "Sleep quality": 4.1, Service: 4.5, Value: 3.9 },
  },
  {
    id: "fjellro",
    type: "Hotel",
    name: "Fjellro Mountain Lodge",
    place: "Geilo, Norway",
    rating: 4.3,
    reviewCount: 312,
    rank: "#2 of 9 hotels in Geilo",
    price: "NOK 1,650 – 2,900 / night",
    tags: ["Ski-in", "Sauna", "Family"],
    gradient: ["#2b3a4a", "#7d8aa0", "#e8e4da"],
    icon: "⛰",
    about: "Timber lodge at the foot of the slopes with an open fire in the lounge, hearty mountain food, and staff who know every trail.",
    amenities: ["Ski-in access", "Ski storage", "Sauna", "Restaurant", "Free parking", "Drying room", "Trail maps & guiding", "Family rooms"],
    subRatings: { Location: 4.6, Cleanliness: 4.4, Rooms: 4.1, "Sleep quality": 4.3, Service: 4.4, Value: 4.0 },
  },
  {
    id: "bryggekanten",
    type: "Restaurant",
    name: "Bryggekanten Sjømat",
    place: "Fredrikstad, Norway",
    rating: 4.7,
    reviewCount: 428,
    rank: "#3 of 96 restaurants in Fredrikstad",
    price: "NOK 250 – 600 · Seafood",
    tags: ["Seafood", "Waterfront", "Local"],
    gradient: ["#5a3a2e", "#c08552", "#f2e8d8"],
    icon: "🦐",
    about: "Harbourside seafood house in the old town — shrimp platters on the wharf, creamy fish soup, and fresh bread.",
    amenities: ["Outdoor seating", "Vegetarian options", "Reservations recommended", "Wine list", "Kids' menu"],
    subRatings: { Food: 4.8, Service: 4.6, Value: 4.4, Atmosphere: 4.7 },
  },
  {
    id: "oslofjordkayak",
    type: "Things to do",
    name: "Oslofjord Kayak Tours",
    place: "Moss, Norway",
    rating: 4.9,
    reviewCount: 187,
    rank: "#1 of 14 activities in Moss",
    price: "NOK 690 / person",
    tags: ["Outdoor", "Guided", "Small group"],
    gradient: ["#11505a", "#3e9aa3", "#cdeae6"],
    icon: "🛶",
    about: "Guided sea-kayak trips between the islands of the outer Oslofjord. Beginners welcome; seals not guaranteed but frequent.",
    amenities: ["Equipment included", "Beginner friendly", "3-hour tour", "Dry bags provided", "Evening departures"],
    subRatings: { Guide: 5.0, Safety: 4.9, Value: 4.7 },
  },
  {
    id: "auroracamp",
    type: "Things to do",
    name: "Aurora Husky Camp",
    place: "Alta, Norway",
    rating: 4.8,
    reviewCount: 503,
    rank: "#2 of 19 activities in Alta",
    price: "NOK 1,490 / person",
    tags: ["Dog sledding", "Winter", "Campfire"],
    gradient: ["#101a33", "#41598a", "#cfe0f2"],
    icon: "🐕",
    about: "Evening dog-sled runs under the northern lights, then reindeer stew and stories around the fire in a lavvo tent.",
    amenities: ["Thermal suits provided", "Campfire dinner", "Hotel pickup", "Small groups", "Photo guide"],
    subRatings: { Experience: 4.9, Guides: 4.9, Value: 4.5 },
  },
];

export const REVIEWS_BY_LISTING = {
  stotvig: [
    { id: 1, author: "Henrik B.", from: "Oslo, Norway", rating: 5, month: "May 2026", tripType: "Couple", title: "The sea view alone is worth the trip", text: "We took a sea-view room and watched the fjord change colour all evening. The spa is genuinely lovely — you swim from the indoor pool straight out into the heated outdoor one, and there are three different saunas plus a cold shower if you're brave. Breakfast was the best we've had at a Norwegian hotel: fresh, varied, and the staff kept everything topped up. Check-in was quick and friendly. We'll be back in winter to try the sea dip.", helpful: 14, verified: true },
    { id: 2, author: "Marte L.", from: "Drammen, Norway", rating: 5, month: "March 2026", tripType: "Family", title: "Our favourite weekend escape", text: "Third visit with the kids and the dog, and it keeps delivering. Rooms are spotless, the beds are excellent, and the New England seaside style makes the whole place feel calm. There are dedicated family hours in the pool, so if you want quiet you just go outside those times. The kids loved the bowling alley and the beach is right there. Dinner in the main restaurant was a real experience.", helpful: 11, verified: true },
    { id: 3, author: "Jon Erik S.", from: "Son, Norway", rating: 2, month: "February 2026", tripType: "Family", title: "Slipping since the management change", text: "Been coming for years, but this stay disappointed. Long queues at both check-in and check-out — apparently a new booking system the staff hadn't been trained on, and we were even shown a previous guest's bill. The entrecôte at dinner was tough and the portions felt small for the price, which is now at Oslo fine-dining level. Bowling cost extra and one lane kept misbehaving. The location and the breakfast are still great, but the focus seems to be on cutting costs.", helpful: 23, verified: true },
    { id: 4, author: "Camilla R.", from: "Bergen, Norway", rating: 4, month: "March 2026", tripType: "Family", title: "Lovely stay, a few small gripes", text: "We arrived early and were allowed to use the spa while we waited for our room — a generous touch. The room was large with a proper double bed (not two singles pushed together), and when it felt cold, one call to reception fixed it. The diner downstairs does a solid burger and milkshake while you watch the bowling. My only complaints: bowling at 500 kr per person feels steep for hotel guests, and an info sheet in the room would save a lot of questions at reception. Breakfast was fantastic.", helpful: 9, verified: true },
    { id: 5, author: "Thomas W.", from: "Gothenburg, Sweden", rating: 3, month: "July 2025", tripType: "Couple", title: "Beautiful hotel, restaurant doesn't match the prices", text: "The setting by the water is gorgeous and the rooms are inviting and spacious. But the restaurant charges gourmet prices for food that doesn't reach that level — my fish soup was tasty but tiny as a main, and my partner's steak was half inedible. Reception staff were warm and professional throughout, which made the contrast with the restaurant more noticeable. Come for the rooms, the spa and the view; manage expectations at dinner.", helpful: 18, verified: true },
    { id: 6, author: "Ingrid Ø.", from: "Trondheim, Norway", rating: 5, month: "April 2025", tripType: "Friends", title: "Quality in every detail", text: "Professional from booking to check-out. The hotel is elegant, clean and well kept, the food was excellent at breakfast, lunch and dinner, and the surroundings are beautiful both inside and out. The bowling was great fun and the spa facility is top class. A hotel I can genuinely recommend.", helpful: 7, verified: true },
    { id: 7, author: "Sofia M.", from: "Stockholm, Sweden", rating: 3, month: "April 2025", tripType: "Family", title: "Don't expect a late night on Sundays", text: "Nice pool area, though there's a bit of a queue for the hot tubs, and bathrobes now cost extra — a strange economy at this price point. Free fruit by the pool is a nice touch. Rooms were clean and the food good. The downside: the bar closed surprisingly early on Sunday with no warning. Spa and food are worth the trip; the evening atmosphere less so.", helpful: 12, verified: true },
    { id: 8, author: "Per Arne K.", from: "Fredrikstad, Norway", rating: 4, month: "January 2026", tripType: "Couple", title: "Winter sea swim and sauna — do it", text: "January is a brilliant time to come. The contrast of jumping in the fjord and then warming up through three saunas is unbeatable. Room was warm and quiet with blackout curtains, breakfast generous. The only thing keeping this from five: small extras add up (bowling, robes) and the in-room TV setup is dated. Still, the core experience — sea, spa, sleep, breakfast — is superb.", helpful: 6, verified: true },
  ],

  nordlys: [
    { id: 11, author: "Emma J.", from: "Manchester, UK", rating: 5, month: "February 2026", tripType: "Couple", title: "Woken at 1am for the aurora — best phone call of my life", text: "We opted in for the aurora wake-up call and on night two it came: green ribbons over the harbour, watched from the rooftop sauna in -8°C. The room was warm, blackout curtains excellent, breakfast had proper coffee and fresh waffles. Staff genuinely seemed to love their town.", helpful: 31, verified: true },
    { id: 12, author: "Lukas F.", from: "Munich, Germany", rating: 4, month: "January 2026", tripType: "Friends", title: "Great base, book the sauna early", text: "Perfect location between the harbour and the main street. The rooftop sauna is the highlight but slots fill up by mid-afternoon — book at check-in. Rooms on the street side hear some weekend noise; ask for harbour side. Fair prices for Tromsø.", helpful: 12, verified: true },
    { id: 13, author: "Astrid H.", from: "Oslo, Norway", rating: 5, month: "March 2026", tripType: "Solo", title: "Solo-traveller friendly", text: "Ate alone at the bistro twice and was made to feel completely at home. The reception printed my bus tickets, lent me ice grips for my boots, and drew a hand-marked map of the best photo spots. Small things, big difference.", helpful: 9, verified: true },
    { id: 14, author: "Daniel P.", from: "Madrid, Spain", rating: 4, month: "December 2025", tripType: "Family", title: "Kids loved it, breakfast gets crowded", text: "Spacious family room with a fjord view. Only gripe: breakfast between 8:30 and 9:30 is a scrum when the tour groups come down. Go early. Otherwise warm, clean, and the staff found us a last-minute husky tour.", helpful: 7, verified: true },
  ],

  havblikk: [
    { id: 21, author: "Marie C.", from: "Lyon, France", rating: 5, month: "September 2025", tripType: "Couple", title: "The most memorable hotel of our lives", text: "Twelve rooms, one shared dinner table, and the ocean roaring on three sides. Dinner was whatever the boats landed that morning — we had halibut so fresh it barely needed anything. No TVs, patchy phone signal, and that's exactly the point. We left two days later feeling like different people.", helpful: 27, verified: true },
    { id: 22, author: "Ole Kristian N.", from: "Bodø, Norway", rating: 5, month: "October 2025", tripType: "Couple", title: "Storm-watching from the deck", text: "We deliberately booked during the autumn storms. Wrapped in wool blankets on the deck with hot toddy while the Atlantic exploded against the rocks — unforgettable. Rooms are simple but immaculate, beds excellent, hosts full of stories.", helpful: 15, verified: true },
    { id: 23, author: "Hannah W.", from: "Berlin, Germany", rating: 4, month: "July 2025", tripType: "Solo", title: "Magical, but know what you're booking", text: "This is a remote lighthouse, not a resort: the last stretch of road is gravel, dinner is one set menu (they handled my vegetarian request well), and there's nothing to 'do' except walk, read, fish and stare at the sea. I loved it. My only niggle is the price of drinks.", helpful: 11, verified: true },
  ],

  granly: [
    { id: 31, author: "Stine A.", from: "Hamar, Norway", rating: 4, month: "February 2026", tripType: "Family", title: "Winter-holiday machine", text: "The outdoor heated pool surrounded by snowy pines is the reason to come — our kids stayed in until their fingers wrinkled. Kids' club gave us two hours of peace daily. Buffet food is fine rather than exciting. Rooms could use a refresh but were clean.", helpful: 8, verified: true },
    { id: 32, author: "Robert E.", from: "Oslo, Norway", rating: 3, month: "March 2026", tripType: "Family", title: "Good bones, tired details", text: "Location and pool are great, but the room carpet had seen better days and the sauna was out of order our whole stay with no discount offered. Ski bus was punctual. Would return at a lower price point.", helpful: 13, verified: true },
    { id: 33, author: "Julie M.", from: "Bergen, Norway", rating: 5, month: "January 2026", tripType: "Friends", title: "Girls' ski weekend done right", text: "Steam room and sauna after the slopes, decent wine list, and big rooms we could share. Staff moved us away from a noisy stag party without us even asking twice. Great value midweek.", helpful: 5, verified: true },
  ],

  kanalhuset: [
    { id: 41, author: "Sarah T.", from: "Dublin, Ireland", rating: 5, month: "May 2026", tripType: "Couple", title: "The free bikes change everything", text: "Grab a bike, follow the canal, get lost — best way to do Copenhagen. The building is gorgeous: old beams, calm rooms, a courtyard café where actual locals have their morning coffee. Rooms are compact, but designed so well you don't mind.", helpful: 19, verified: true },
    { id: 42, author: "Mikkel D.", from: "Aarhus, Denmark", rating: 4, month: "April 2026", tripType: "Business", title: "Charming, slightly creaky", text: "Beautiful conversion and a great organic breakfast. Be aware the old wooden floors mean you hear footsteps above you — pack earplugs or ask for the top floor. Twenty minutes' walk to the centre, or six by bike.", helpful: 10, verified: true },
    { id: 43, author: "Nina V.", from: "Hamburg, Germany", rating: 4, month: "June 2025", tripType: "Family", title: "Canal-side calm with kids", text: "We had the family room facing the canal — the kids counted boats every morning. Staff lent us a cargo bike for the little one. Only minus is the tiny bathroom. Would absolutely return.", helpful: 6, verified: true },
  ],

  lindencourt: [
    { id: 51, author: "Margaret H.", from: "Boston, USA", rating: 5, month: "April 2026", tripType: "Couple", title: "Exactly the London I wanted", text: "A creaky Georgian townhouse on a leafy square, afternoon tea done properly, and the British Museum a five-minute stroll. Our room was small but full of character, and the concierge got us last-minute theatre tickets twice.", helpful: 22, verified: true },
    { id: 52, author: "James O.", from: "Sydney, Australia", rating: 3, month: "March 2026", tripType: "Business", title: "Charm doesn't fix the plumbing", text: "Lovely public rooms and staff, but my shower alternated between scalding and freezing, and the radiator clanked all night. For this price in London I expect the basics nailed. They did move me on night two, to be fair.", helpful: 17, verified: true },
    { id: 53, author: "Priya K.", from: "Mumbai, India", rating: 4, month: "May 2026", tripType: "Family", title: "Location is the star", text: "Bloomsbury is calm, green and walkable — perfect with kids who tire of the Tube. Rooms are snug for four; book two if you can. The library bar's hot chocolate was my daughters' highlight of the whole trip.", helpful: 8, verified: true },
  ],

  sakurabay: [
    { id: 61, author: "Claire D.", from: "Paris, France", rating: 5, month: "April 2026", tripType: "Couple", title: "The kaiseki dinner made me cry a little", text: "Ten courses served in our tatami room by the kindest hostess, each plate explaining the season. Then a private open-air onsen under the stars. Fuji showed up at breakfast, pink in the dawn. Worth every yen.", helpful: 40, verified: true },
    { id: 62, author: "Kenji M.", from: "Tokyo, Japan", rating: 5, month: "November 2025", tripType: "Couple", title: "Autumn leaves season — book months ahead", text: "The valley turns red and gold in late November and the rotenburo looks straight into it. Service is anticipatory in the best ryokan tradition: futons appeared while we ate, taxis materialised before we asked.", helpful: 18, verified: true },
    { id: 63, author: "Laura S.", from: "Toronto, Canada", rating: 4, month: "October 2025", tripType: "Friends", title: "Stunning, with cultural homework", text: "Read up on ryokan etiquette before you go — meal times are fixed, tattoos need covering in the public baths (private baths are fine), and the futon is firmer than a Western bed. Embrace it and this place is magic.", helpful: 14, verified: true },
  ],

  casadelfaro: [
    { id: 71, author: "Anna B.", from: "Vienna, Austria", rating: 5, month: "June 2025", tripType: "Couple", title: "That terrace, that view", text: "Breakfast on a cliffside terrace with the harbour below and lemon trees around you. Rooms are simple but spotless, and the welcome limoncello sets the tone. Yes, there are many stairs. The porter carried our bags up with a smile.", helpful: 25, verified: true },
    { id: 72, author: "Mark R.", from: "Chicago, USA", rating: 3, month: "July 2025", tripType: "Family", title: "Beautiful but brutal in a heatwave", text: "No elevator and about 90 steps from the harbour — with luggage and two kids in 34°C, that's a workout. AC in the room struggled on the hottest days. The view almost makes up for it. Almost. Travel light and come in shoulder season.", helpful: 21, verified: true },
    { id: 73, author: "Giulia P.", from: "Milan, Italy", rating: 4, month: "September 2025", tripType: "Couple", title: "September is the secret", text: "Crowds gone, sea still warm, and the sunset from the upper terrace is absurd. Rooms 5 and 6 have the best views. Breakfast pastries come from the bakery below and sell out — go before 9.", helpful: 9, verified: true },
  ],

  fjellro: [
    { id: 81, author: "Lise T.", from: "Oslo, Norway", rating: 4, month: "February 2026", tripType: "Family", title: "Cosy after a day on the slopes", text: "Ski-in convenience is real, sauna small but hot, dinner buffet decent. Rooms a little tired but clean, and the drying room actually dries things overnight.", helpful: 4, verified: true },
    { id: 82, author: "Anders H.", from: "Bergen, Norway", rating: 5, month: "March 2026", tripType: "Friends", title: "Exactly what a mountain lodge should be", text: "Open fire in the lounge, hearty food, staff who know the trails and the snow report by heart. We'll return next season.", helpful: 6, verified: true },
    { id: 83, author: "Petra S.", from: "Utrecht, Netherlands", rating: 4, month: "January 2026", tripType: "Couple", title: "Honest mountain comfort", text: "Not luxurious and not pretending to be. Warm rooms, big breakfasts, waxing bench in the ski room. Wifi is weak in the far wing — fine by us.", helpful: 3, verified: true },
  ],

  bryggekanten: [
    { id: 91, author: "Eva N.", from: "Sarpsborg, Norway", rating: 5, month: "May 2026", tripType: "Couple", title: "Freshest shrimp in Østfold", text: "Sat on the wharf with a shrimp platter and white wine. Simple, perfect, fairly priced.", helpful: 8, verified: true },
    { id: 92, author: "Karl J.", from: "Halden, Norway", rating: 4, month: "April 2026", tripType: "Family", title: "Great fish soup, book ahead", text: "Busy on weekends — reserve. The creamy fish soup and fresh bread were the highlights. Kids' menu is actual food, not just nuggets.", helpful: 3, verified: true },
    { id: 93, author: "Tone B.", from: "Fredrikstad, Norway", rating: 5, month: "June 2025", tripType: "Friends", title: "Where we take all our visitors", text: "Old-town setting, water lapping under the wharf, and a kitchen that respects the fish. Service was relaxed in the good way.", helpful: 5, verified: true },
  ],

  oslofjordkayak: [
    { id: 101, author: "Nora F.", from: "Moss, Norway", rating: 5, month: "June 2026", tripType: "Solo", title: "Magical evening paddle", text: "Our guide read the water and the weather perfectly. Saw seals near the skerries. Total beginners welcome — I'd never kayaked before.", helpful: 9, verified: true },
    { id: 102, author: "Ben A.", from: "London, UK", rating: 5, month: "May 2026", tripType: "Couple", title: "Highlight of our Norway trip", text: "Three hours flew by. Small group of six, brand-new kayaks, dry bags provided, and a swim stop on an island beach. Book the sunset slot.", helpful: 6, verified: true },
  ],

  auroracamp: [
    { id: 111, author: "Yuki T.", from: "Osaka, Japan", rating: 5, month: "January 2026", tripType: "Couple", title: "Huskies first, aurora as the encore", text: "The dogs are the stars — friendly, loud, desperate to run. Halfway through the run the sky went green above the sled. Then reindeer stew by the fire in the lavvo. Thermal suits kept us warm at -15°C.", helpful: 16, verified: true },
    { id: 112, author: "Connor M.", from: "Edinburgh, UK", rating: 4, month: "December 2025", tripType: "Friends", title: "Brilliant even without lights", text: "Clouds rolled in and we saw no aurora, but the sledding, the fire and the guides' stories carried the night anyway. They were upfront that lights are never guaranteed, which I respected.", helpful: 11, verified: true },
  ],
};
